version: '3'

services:
  postgres:
    image: postgres:12.20-bullseye
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_schema_ddl.sql:/docker-entrypoint-initdb.d/pg_schema_ddl.sql  # Mount the script
    ports:
      - 5432:5432
    networks:
      - my-network

  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - my-network

volumes:
  postgres_data:
  mongo_data:

networks:
  my-network:
    driver: bridge

name: api_practice  # Choose a unique project name